
module DDC.Main.Help where

-- | The command-line help page.
help :: String
help    = unlines
        [ "The Disciplined Disciple Compiler, version 0.3.0"
        , ""
        , " General:"
        , "       -help                  Display this help."
        , ""
        , " Compilation:"
        , "       -make         FILE     Compile a module into an executable file."
        , "  -c,  -compile      FILE     Compile a module into an object file."
        , ""
        , "       -library      DIR      Path to the base library code (./code)"
        , ""
        , "       -fvia-llvm             Compile via the LLVM backend  (default)"
        , "       -fvia-c                Compile via the C backend."
        , ""
        , "  -o,  -output       FILE     Redirect output to this file."
        , "       -output-dir   DIR      Redirect output to this directory."
        , ""
        , "       -keep-ll-files         Keep intermediate .llvm files."
        , "       -keep-c-files          Keep intermediate .c files."
        , "       -keep-s-files          Keep intermediate .s files."
        , ""
        , " Optimisation:"
        , "       -O0                    No optimisations.             (default)"
        , "  -O,  -O1                    Do standard optimisations."
        , ""
        , " Runtime for compiled program:"
        , "       -run-heap     BYTES    Size of fixed heap            (65536)"
        , ""
        , " Checking:"
        , "       -check        FILE     Parse and type check a core module."
        , ""
        , " Transformation:"
        , "       -load         FILE     Parse, type check and transform a module."
        , "       -trans        TRANS    Set the transformation to use with -load."
        , "       -with         FILE     Use this module for inliner templates with -load."
        , ""
        , " Conversion:"
        , "       -to-salt      FILE     Convert a module to Disciple Core Salt."
        , "       -to-c         FILE     Convert a module to C code."
        , "       -to-llvm      FILE     Convert a module to LLVM code."
        , ""
        , " Debugging:"
        , "       -dump                  Dump intermediate representations."
        , "       -ast          FILE     Pretty print the AST of a module."
        , "       -print-builder         Print external builder info for this platform." 
        , "" ]

        
